language: java
jdk:
- openjdk8
addons:
    apt:
	addons:
      packages:
        ant
 	sonarcloud:
 		organization:EmDonato
 token:
 secure:875861271dc6e7bf010fc75149ba40ff59edbbeb
script:
 - ant build 
 - sonar-scanner